Repository KOSTA-devops-2team/Wedder-FE, pull requests merged in 2024-07, with the labels that each got.

#3 [PR] FE-VSplan
  .vscode/settings.json
  assets/images/Matari.png
  assets/images/arrow_drop_down.png
  assets/images/cake.png
  assets/images/mail.png
  assets/images/menu.png
  assets/images/phone_iphone.png
  assets/images/studioimage.jpg
  css/common/reset.css
  css/main/main.css
  css/mypage/mypage.css
  html/main/main.html
  html/mypage/mypage.html
  js/mypage/mypage.js
Labels: 🕹️ feature, jongwon

#4 feat : [FE] Reservation
  html/main/main.html
Labels: 🕹️ feature, jeonghwa

#32 feat : [FE] 공통 footer, header 완성
  components/footer/footer.html
  components/header/header.html
  css/common/footer/footer.css
  css/common/header/header.css
  css/common/reset.css
  html/main/main.html
Labels: hyewon, FE

#34 [PR] FE - Wedder 메인페이지
  assets/images/left-right.png
  assets/images/main-package1-1.png
  assets/images/main-package2-1.png
  assets/images/main-package2-2.png
  assets/images/main-package3-1.png
  assets/images/main-package3-2.png
  assets/images/main0.png
  assets/images/main1.png
  assets/images/main2.png
  components/header/header.html
  css/common/header/header.css
  css/main/main.css
  css/weddingHall/weddingHallList.css
  html/main/main.html
  html/weddingHall/weddingHallList.html
Labels: hyewon, 🍋 front-end

#46 feat : [FE] 스드메 예약 카테고리 1차 완성
  assets/images/Reservation-CG-Makeup.png
  assets/images/Reservation-CG-Package.png
  assets/images/Reservation-CG-Studio.png
  assets/images/Resevation-CG-Dress.png
  css/reservation/Reservation-category.css
  html/reservation/Reservation-category.html
Labels: jeonghwa, 🍋 front-end

#48 feat : [FE] 스드메 예약페이지 CSS수정
  css/reservation/Reservation-category.css
  html/reservation/Reservation-category.html
Labels: jeonghwa, 🍋 front-end

#53 [PR] FE - 웨딩홀 조건 검색 후 지도로 보기
  assets/images/Matari.png
  assets/images/Reservation-CG-Makeup.png
  assets/images/Reservation-CG-Package.png
  assets/images/Reservation-CG-Studio.png
  assets/images/Resevation-CG-Dress.png
  assets/images/appstore.png
  assets/images/arrow_drop_down.png
  assets/images/cake.png
  assets/images/down-arrow.png
  assets/images/footer.png
  assets/images/googlestore.png
  assets/images/heart-bold.png
  assets/images/heart.png
  assets/images/left-right.png
  assets/images/mail.png
  assets/images/main-package1-1.png
  assets/images/main-package2-1.png
  assets/images/main-package2-2.png
  assets/images/main-package3-1.png
  assets/images/main-package3-2.png
  assets/images/main0.png
  assets/images/main1.png
  assets/images/main2.png
  assets/images/map.png
  assets/images/menu.png
  assets/images/mmm.png
  assets/images/phone_iphone.png
  assets/images/rate_review_24dp_5F6368_FILL0_wght400_GRAD0_opsz24.png
  assets/images/search-icon.png
  assets/images/star-1.png
  assets/images/star-2.png
  assets/images/studioimage.jpg
  assets/images/thumbnail.PNG
  assets/images/wedder-logo.png
  assets/images/weddinghall1.jpg
  assets/images/weddinghall2.jpg
  components/footer/footer.html
  components/header/header.html
  css/common/footer/footer.css
  css/common/header/header.css
  css/common/reset.css
  css/main/main.css
  css/reservation/reservationCategory.css
  css/weddingHall/mapViewWithFilters.css
  css/weddingHall/weddingHallList.css
  html/Package/packageMain.html
  html/calculator/quoteCal.html
  html/main/main.html
  html/mypage/mypage.html
  html/reservation/Reservation-category.html
  html/reservation/reservationCategory.html
  html/weddingHall/mapViewWithFilters.html
  html/weddingHall/weddingHallList.html
  js/weddingHall/mapViewWithFilters.js
Labels: hyewon, 🍋 front-end

#57 [PR] FE - git pull origin develop
  assets/images/BestPackage1.png
  assets/images/BestPackage2.png
  assets/images/BestPackage3.png
  assets/images/BestPackage4.png
  assets/images/RecommendPic1.png
  assets/images/RecommendPic2.png
  assets/images/RecommendPic3.png
  assets/images/RecommendPic4.png
  assets/images/step1.png
  assets/images/step2.png
  assets/images/step3.png
  assets/images/step4.png
  css/calculator/quoteCal.css
  css/package/packageDetails.css
  css/package/packageMain.css
  html/Package/packageDetails.html
  html/Package/packageMain.html
  html/calculator/quoteCal.html
Labels: junseok, 🍋 front-end

#59 [PR] FE - git pull Origin develop
  css/LikeList/LikeList.css
  html/LikeList/LikeList.html
  html/main/main.html
Labels: 🕹️ feature, jongwon

#60 [PR] FE LikeList HTML,CSS End
  css/LikeList/LikeList.css
Labels: 🕹️ feature, jongwon, 🍋 front-end

#61 [PR] FE -My 결제 내역 테이블 작성중
  css/myPayment/myPayment.css
  html/LikeList/LikeList.html
  html/myPayment/myPayment.html
  js/myPayment/myPayment.js
Labels: 🕹️ feature, jongwon, 🍋 front-end

#63 feat : [FE] fixed likelist.css
  css/LikeList/LikeList.css
  css/myPayment/myPayment.css
  html/LikeList/LikeList.html
  html/myPayment/myPayment.html
Labels: 🕹️ feature, jongwon, 🍋 front-end

#64 [PR] FE 드랍다운 형식 option형식으로 변경
  css/mypage/mypage.css
  html/mypage/mypage.html
  js/mypage/mypage.js
Labels: 🕹️ feature, jongwon, 🍋 front-end

#65 [PR] FE git pull 받아서 merge 된 내용 push
  html/detailedReservation/detailedReservation.html
  js/detaiedReservation/detaiedReservation.js
Labels: 🕹️ feature, jongwon, 🍋 front-end

#66 [PR] FE - 웨딩홀 상세페이지 일부 완성
  components/header/header.html
  css/weddingHall/weddingHallDetail.css
  html/weddingHall/weddingHallDetail.html
  js/weddingHall/weddingHallDetail.js
Labels: hyewon, 🍋 front-end

#67 [PR] FE - 패키지 상세페이지 1차 완성
  css/estimate/estimateCal.css
  css/package/packageDetails.css
  css/package/packageMain.css
  html/Package/packageDetails.html
  html/Package/packageMain.html
  html/estimate/estimateCal.html
Labels: junseok, 🍋 front-end

#68 [PR] FE : DEVELOP에서 머지 받은 내용 푸쉬
  css/detailedReservation/detailedReservation.css
  html/detailedReservation/detailedReservation.html
Labels: 🕹️ feature, jongwon, 🍋 front-end

#70 [PR] FE - 디자인 변경
  css/myPayment/myPayment.css
  html/myPayment/myPayment.html
Labels: 🕹️ feature, jongwon, 🍋 front-end

#71 [PR] FE - design 수정
  css/LikeList/LikeList.css
  html/LikeList/LikeList.html
Labels: 🕹️ feature, jongwon, 🍋 front-end

#73 [PR] FE - th,td reset.css에서 제거
  html/detailedReservation/detailedReservation.html
  js/detailedReservation/detailedReservation.js
Labels: 🕹️ feature, jongwon, 🍋 front-end

#75 [PR] FE - 패키지 상세페이지
  assets/images/dersssThumbnail.png
  assets/images/empty-heart.png
  assets/images/full-heart.png
  assets/images/makeupThumbnail.png
  assets/images/weddingThumbnail.png
  css/package/packageDetails.css
  html/Package/packageDetails.html
  js/package/packageDetails.js
Labels: junseok, 🍋 front-end

#77 [PR] FE - 웨딩홀 상세페이지
  css/weddingHall/mapViewWithFilters.css
  css/weddingHall/weddingHallDetail.css
  html/weddingHall/weddingHallDetail.html
  js/weddingHall/weddingHallDetail.js
Labels: hyewon, 🍋 front-end

#83 [PR] FE - 웨딩홀 방문 페이지 (예약 날짜, 예식 희망일 완성)
  assets/images/calendar-july.png
  assets/images/calendar-nov.png
  assets/images/visitReservation-banner.png
  assets/images/visitReservation-banner1.png
  assets/images/visitReservation-bannerImg.png
  css/reservation/ReservationCategory.css
  css/visitReservation/visitReserveDate.css
  css/visitReservation/visitReserveExpectancy.css
  html/reservation/reservationCategory.html
  html/visitReservation/visitReserveDate.html
  html/visitReservation/visitReserveExpectancy.html
Labels: jeonghwa, 🍋 front-end

#80 [PR] FE - 공통 페이지네이션 1차 완성
  components/pagination/pagination.html
  css/common/pagination/pagination.css
  js/pagination/pagination.js
Labels: hyewon, 🍋 front-end

#82 [PR] FE - 세부 옵션 견적서 페이지 1차 완성
  assets/images/estimateBanner.png
  assets/images/estimateDetails1.png
  assets/images/estimateDetails2.png
  css/estimate/estimateCal.css
  css/estimate/estimateDetails.css
  css/package/packageMain.css
  html/estimate/estimateCal.html
  html/estimate/estimateDetails.html
Labels: junseok, 🍋 front-end

#81 [PR] FE - 웨딩홀 상세페이지 업체 이미지 캐러셀, 모달창 연결
  css/weddingHall/reviewSearchModal.css
  css/weddingHall/weddingHallDetail.css
  html/weddingHall/reviewSearchModal.html
  html/weddingHall/weddingHallDetail.html
  js/weddingHall/reviewSearchModal.js
  js/weddingHall/weddingHallDetail.js
Labels: hyewon, 🍋 front-end

#87 [PR] FE - 헤더 슬라이딩 애니메이션 추가
  components/header/header.html
  css/common/header/header.css
  html/main/main.html
  html/reservation/reservationCategory.html
  js/main/main.js
Labels: hyewon, 🍋 front-end

#89 [PR] FE - 페이지네이션 컴포넌트화
  components/pagination/pagination.html
  css/common/pagination/pagination.css
  html/weddingHall/weddingHallList.html
  js/pagination/pagination.js
Labels: hyewon

#90 [PR] FE - 관리자페이지 메인
  components/header/header.html
  components/sidebar/sidebarAdmin.html
  css/admin/adminMain.css
  css/common/header/header.css
  css/common/sidebar/sidebarAdmin.css
  html/admin/adminMain.html
  js/admin/adminMain.js
  js/header/header.js
  js/main/main.js
Labels: hyewon, 🍋 front-end

#92 [PR] FE - 패키지 메인페이지 슬라이드 완성
  css/estimate/estimateDetails.css
  css/package/packageMain.css
  css/package/swiper.css
  html/Package/packageMain.html
  html/estimate/estimateDetails.html
  js/package/packageMain.js
  js/package/swiper.js
Labels: junseok, 🍋 front-end

#93 [PR] FE - partnersTopPicks 전체적인 디자인 변경
  css/common/reset.css
  css/mypage/detailedReservation.css
  css/mypage/myPayment.css
  css/mypage/partnersTopPicks.css
  css/reservation/reservationCategory.css
  html/mypage/detailedReservation.html
  html/mypage/partnersTopPicks.html
  js/main/main.js
  js/mypage/detailedReservation.js
  js/mypage/partnersTopPicks.js
Labels: 🕹️ feature, jongwon, 🍋 front-end

#95 [PR] FE - 버그 픽스 중 백업 후 복구중
  css/reservation/reservationCategory.css
Labels: 🐞 bug, 🕹️ feature, jongwon, 🍋 front-end

#97 [PR] FE - 웨딩홀 결제페이지
  assets/images/kakao.png
  assets/images/naver.png
  assets/images/payco.png
  assets/images/samsung.png
  assets/images/toss.png
  css/common/reset.css
  css/weddingHall/weddingHallPayment.css
  html/weddingHall/weddingHallPayment.html
  js/weddingHall/weddingHallPayment.js
Labels: hyewon, 🍋 front-end

#100 [PR] FE - 대문자 변경에서 소문자 변경중
  html/login/login.html
Labels: hyukzun

#101 [PR] FE - 관리자페이지 (고객관리 상세페이지)
  components/header/header.html
  components/header/headerV2.html
  css/admin/customerDetail.css
  css/admin/quoteModal.css
  css/common/header/header.css
  css/common/header/headerV2.css
  html/admin/adminMain.html
  html/admin/customerDetail.html
  html/admin/customerList.html
  html/admin/quoteModal.html
  html/weddingHall/mapViewWithFilters.html
  js/admin/customerDetail.js
  js/main/main.js
Labels: hyewon

#102 [PR] FE - 패키지 최종견적서 완성
  assets/images/High-endPack.png
  assets/images/PremiumPack.png
  assets/images/basicPack.png
  assets/images/dressThumbnail.png
  assets/images/standardPack.png
  css/estimate/estimateDetails.css
  css/estimate/estimateFinal.css
  css/package/packageRecommend.css
  html/Package/packageRecommend.html
  html/estimate/estimateCal.html
  html/estimate/estimateDetails.html
  html/estimate/estimateFinal.html
Labels: junseok, 🍋 front-end

#112 [PR] FE - 브랜치 변경
  css/estimate/estimateCal.css
  css/estimate/estimateDetails.css
  css/estimate/estimateFinal.css
  css/package/packageDetails.css
  css/package/packageMain.css
  css/package/packageRecommend.css
  html/Package/packageDetails.html
  html/Package/packageRecommend.html
  html/estimate/estimateCal.html
  html/estimate/estimateDetails.html
  html/estimate/estimateFinal.html
Labels: junseok, 🍋 front-end

#114 [PR] FE - 2차 점검 페이지 수정
  assets/images/reserve-studio-company.png
  css/reservation/reservationCategory.css
  css/reservation/reservationPayment.css
  css/reservation/reservationSelectCompany.css
  css/reservation/reservationSelectDate.css
  css/reservation/reservationSelectOptions.css
  css/visitReservation/reservationModal.css
  css/visitReservation/visitReserveDate.css
  css/visitReservation/visitReserveExpectancy.css
  css/visitReservation/visitReserveInfo.css
  html/reservation/reservationCategory.html
  html/reservation/reservationPayment.html
  html/reservation/reservationSelectCompany.html
  html/reservation/reservationSelectDate.html
  html/reservation/reservationSelectOptions.html
  html/visitReservation/reservationModal.html
  html/visitReservation/visitReserveDate.html
  html/visitReservation/visitReserveExpectancy.html
  html/visitReservation/visitReserveInfo.html
  js/reservation/reservationPayment.js
  js/reservation/reservationSelectCompany.js
  js/reservation/reservationSelectDate.js
  js/visitReservation/visitReserveInfo.js
Labels: jeonghwa, 🍋 front-end

#115 [PR] FE - 로그인생성js 및 패스워드 생성js
  html/login/passwordJoin.html
  js/login/IDJoin.js
  js/login/passwordJoin.js
Labels: hyukzun

#88 [PR] FE - 웨딩홀 후기 모달창
  assets/images/blog.png
  assets/images/cafe.png
  css/reservation/reservationCategory.css
  css/weddingHall/reviewSearchModal.css
  html/weddingHall/reviewSearchModal.html
Labels: hyewon

#116 [PR] FE - 프론트 2차 점검 디자인 수정
  assets/images/002.png
  assets/images/003.png
  assets/images/instagram1.png
  assets/images/instagram2.png
  assets/images/logo-v1.png
  assets/images/section-compare2.png
  assets/images/section-estimate1.png
  assets/images/section-estimate2.png
  assets/images/section-estimate3.png
  assets/images/section-pay1.png
  assets/images/section-pay2.png
  assets/images/section-pay3.png
  assets/images/section-share1.png
  assets/images/section-share2.png
  assets/images/section-share3.png
  components/footer/footerV2.html
  components/header/headerV2.html
  components/sidebar/sidebarAdmin.html
  css/admin/adminMain.css
  css/admin/customerDetail.css
  css/admin/customerList.css
  css/admin/quoteModal.css
  css/common/footer/footer.css
  css/common/footer/footerV2.css
  css/common/header/headerV2.css
  css/main/main.css
  css/package/packageMain.css
  css/weddingHall/weddingHallList.css
  html/admin/adminMain.html
  html/admin/customerDetail.html
  html/admin/customerList.html
  html/admin/quoteModal.html
  html/main/main.html
  html/weddingHall/weddingHallList.html
  js/admin/adminMain.js
  js/admin/customerDetail.js
  js/admin/customerList.js
  js/main/main.js
Labels: 🐞 bug, hyewon, 🍋 front-end

#118 [PR] FE - 견적함 페이지, 자바스크립트 파일들 추가
  assets/images/arrow-icon.png
  assets/images/storage-dress.jpg
  assets/images/storage-makeup.png
  assets/images/storage-studio.jpg
  css/mypage/estimateStorage.css
  css/reservation/reservationCategory.css
  css/reservation/reservationPayment.css
  css/reservation/reservationSelectCompany.css
  css/reservation/reservationSelectDate.css
  css/reservation/reservationSelectOptions.css
  css/visitReservation/reservationModal.css
  css/visitReservation/visitReserveDate.css
  css/visitReservation/visitReserveExpectancy.css
  css/visitReservation/visitReserveInfo.css
  html/mypage/estimateStorage.html
  html/reservation/reservationCategory.html
  html/reservation/reservationSelectCompany.html
  html/reservation/reservationSelectDate.html
  html/reservation/reservationSelectOptions.html
  html/visitReservation/reservationModal.html
  html/visitReservation/visitReserveDate.html
  html/visitReservation/visitReserveInfo.html
  js/mypage/estimateStorage.js
  js/reservation/reservationCategory.js
  js/reservation/reservationSelectCompany.js
  js/reservation/reservationSelectDate.js
  js/reservation/reservationSelectOptions.js
  js/visitReservation/visitReserveDate.js
  js/visitReservation/visitReserveInfo.js
Labels: jeonghwa, 🍋 front-end

#119 [PR] FE - 프론트 2차 점검 디자인 수정
  css/weddingHall/mapViewWithFilters.css
  css/weddingHall/reviewSearchModal.css
  html/main/main.html
  html/weddingHall/mapViewWithFilters.html
  html/weddingHall/reviewSearchModal.html
  html/weddingHall/weddingHallDetail.html
  js/weddingHall/weddingHallDetail.js
Labels: 🐞 bug, 🍋 front-end

#120 [PR] FE - 프론트 2차 점검 디자인 수정
  assets/images/icon-calander.png
  assets/images/icon-cart.png
  assets/images/icon-document.png
  assets/images/icon-payment.png
  css/estimate/estimateCal.css
  css/estimate/estimateDetails.css
  css/estimate/estimateFinal.css
  css/package/packageMain.css
  css/package/packageRecommend.css
  html/Package/packageDetails.html
  html/Package/packageMain.html
  html/Package/packageRecommend.html
  html/estimate/estimateCal.html
  html/estimate/estimateDetails.html
  html/estimate/estimateFinal.html
Labels: junseok, 🍋 front-end

#121 [PR] FE - 프론트 2차 점검 디자인 수정
  css/login/login.css
  html/login/login.html
  js/login/IDJoin.js
  js/login/login.js
Labels: hyukzun

#125 [PR] FE - 프론트 2차 점검 디자인 수정
  css/login/IDJoin.css
  css/login/agreement.css
  css/login/joinPaly.css
  css/login/law.css
  css/login/login.css
  css/login/passfind.css
  css/login/passwordJoin.css
  css/login/useLaw.css
  html/login/IDJoin.html
  html/login/agreement.html
  html/login/clearmessage.html
  html/login/joinPaly.html
  html/login/login.html
  html/login/marketing.html
  html/login/passfind.html
  html/login/passwordJoin.html
  html/login/privacy.html
  html/login/uselaw.html
  js/login/IDJoin.js
  js/login/agreement.js
  js/login/joinPaly.js
  js/login/law.js
  js/login/login.js
  js/login/passfind.js
  js/login/passwordJoin.js
Labels: hyukzun
