Repository KOSTA-devops-2team/Wedder-FE, pull requests merged in 2024-08, with the labels that each got.

#131 [PR] FE - 풀 리퀘스트 후 기능 2가지 추가후 머지
  components/sidebar/navibar.html
  components/sidebar/sidebarMyPage.html
  css/mypage/myPayment.css
  css/mypage/mypageNaviba.css
  css/mypage/paymentDetail.css
  html/mypage/myPayment.html
  html/mypage/paymentDetail.html
  html/mypage/reservationDetail.html
Labels: 🕹️ feature, jongwon, 🍋 front-end

#133 [PR] FE 스드메 페이지 추가
  assets/images/RecommendPic1.png
  assets/images/RecommendPic2.png
  assets/images/RecommendPic3.png
  assets/images/RecommendPic4.png
  assets/images/dress-10.jpg
  assets/images/dress-11.jpg
  assets/images/dress-12.jpg
  assets/images/dress-8.jpg
  assets/images/dress-9.jpg
  assets/images/dress-map.png
  assets/images/estimateDetails1.png
  assets/images/estimateDetails2.png
  assets/images/makeup-10.jpg
  assets/images/makeup-11.jpg
  assets/images/makeup-12.jpg
  assets/images/makeup-7.jpg
  assets/images/makeup-8.jpg
  assets/images/makeup-9.jpg
  assets/images/makeup-map.png
  assets/images/option10.png
  assets/images/option11.png
  assets/images/option2.png
  assets/images/option4.png
  assets/images/option5.png
  assets/images/option6.png
  assets/images/option7.png
  assets/images/option8.png
  assets/images/option9.jpg
  assets/images/studio-10.jpg
  assets/images/studio-11.jpg
  assets/images/studio-12.jpg
  assets/images/studio-13.jpg
  assets/images/studio-14.jpg
  assets/images/studio-8.jpg
  assets/images/studio-9.jpg
  assets/images/studio-map.png
  assets/images/trashcan.png
  css/dress/dressDetail.css
  css/mypage/estimateStorage.css
  css/reservation/reservationPayment.css
  css/reservation/reservationSelectDate.css
  css/reservation/reservationSelectOptions.css
  css/studio/studioDetail.css
  html/dress/dressDetail.html
  html/dress/dressList.html
  html/makeup/makeupDetail.html
  html/mypage/estimateStorage.html
  html/reservation/reservationPayment.html
  html/reservation/reservationSelectDate.html
  html/reservation/reservationSelectOptions.html
  html/studio/studioDetail.html
  js/dress/dressDetail.js
  js/makeup/makeupDetail.js
  js/mypage/estimateStorage.js
  js/reservation/reservationSelectOptions.js
  js/studio/studioDetail.js
Labels: jeonghwa, 🍋 front-end

#135 [PR] FE - 금요일 Pull Request
  css/estimate/estimateCalculator.css
  css/estimate/estimateDetail.css
  css/estimate/estimateFinal.css
  css/login/IDJoin.css
  css/login/agreement.css
  css/login/clearmessage.css
  css/login/consentForm.css
  css/login/emailVertify.css
  css/login/joinPaly.css
  css/login/law.css
  css/login/login.css
  css/login/passwordJoin.css
  css/login/useLaw.css
  css/package/packageMain.css
  html/estimate/estimateCalculator.html
  html/estimate/estimateDetail.html
  html/estimate/estimateFinal.html
  html/login/IDJoin.html
  html/login/agreement.html
  html/login/consentForm.html
  html/login/emailVertify.html
  html/login/joinPaly.html
  html/login/login.html
  html/login/marketing.html
  html/login/passfind.html
  html/login/passwordJoin.html
  html/login/privacy.html
  html/package/packageMain.html
  js/estimate/estimateCalculator.js
  js/estimate/estimateFinal.js
  js/login/agreement.js
  js/login/consentForm.js
  js/login/emailVertify.js
  js/login/joinPaly.js
  js/login/login.js
  js/login/passfind.js
  js/login/passwordJoin.js
Labels: junseok, 🍋 front-end

#136 [PR] 회원가입 페이지 1차 완성
  assets/images/icon-camera.png
  assets/images/profile.png
  assets/images/user-profile.png
  css/common/reset.css
  css/login/signUp.css
  css/mypage/estimateStorage.css
  html/login/signUp.html
  html/mypage/estimateStorage.html
  js/login/signUp.js
  js/mypage/estimateStorage.js
Labels: jeonghwa, 🍋 front-end

#137 [PR] 견적서 디자인 수정 및 헤더 정리
  components/sidebar/navibar.html
  components/sidebar/sidebarMyPage.html
  css/dress/dressDetail.css
  css/mypage/LikeList.css
  css/mypage/estimateStorage.css
  css/mypage/myPayment.css
  css/mypage/mypage.css
  css/mypage/mypageNaviba.css
  css/mypage/reservationDetail.css
  css/mypage/reservationList.css
  html/mypage/estimateStorage.html
  html/mypage/likeList.html
  html/mypage/myPayment.html
  html/mypage/mypage.html
  html/mypage/paymentDetail.html
  html/mypage/reservationDetail.html
  html/mypage/reservationList.html
  js/mypage/LikeList.js
  js/mypage/reservationList.js
Labels: 🕹️ feature, jongwon, 🍋 front-end

#140 [PR] FE - 로그인 페이지 css 수정
  css/login/login.css
Labels: hyewon

#141 chore: [FE] 회원가입 페이지 수정
  css/login/login.css
  css/login/signUp.css
  html/login/signUp.html
  js/login/signUp.js
Labels: jeonghwa, 🍋 front-end
